name: Playwright Tests
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  playwright:
    name: Playwright Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.44.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v3
        with:
         path: 'c:\hostedtoolcache\windows\Java_Microsoft_jdk\17.0.3\x64'
         key: ${{ runner.os }}-jdk-17.0.3
         restore-keys: ${{ runner.os }}-jdk-17.0.3

      - name: Install Java
        if: ${{steps.cache-java.outputs.cache-hit != 'true'}} # condition to check if old installation is available in cache
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
          architecture: 'x64'
         
      - name: Verify Java installation
        run: |
          echo "java version:"
          java -version

      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: xvfb-run npm run test:chromium:test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: my-report/
          retention-days: 30
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
      
      - name: Generate Allure report
        run: |
          npm install -D allure-commandline
          npx allure generate ./allure-results --clean
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: my-report/
          retention-days: 30
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: all-blob-reports
          path: blob-report
          retention-days: 1